### PR TITLE
Bump copyright year in README.md

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR bumps the copyright year in the README.md file.

Happy new year! 🎉

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim

Happy New Year!

You might like to browse https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated where one of the answers says:

"Technically, you should update a copyright year only if you made contributions to the work during that year. So if your website hasn't been updated in a given year, there is no ground to touch the file just to update the year."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Happy new year to you too! 

Thank you for the link. 

I think we can still update the copyright, but we can also let it unchanged for now and only update it if there is really a change.

I suggest that @dsarkar or somebody else from the Open Source team decides how to proceed. 

---

What I myself asked me during the process of creating all the PRs is wether it is correct to only write 
©2022 now or if ©2020-2022 is correct. 

[Amazon](https://www.amazon.de/) writes it as ©1996 - 2022 while [Apple](https://www.apple.com/) writes it as ©2022.

What do you think? I went with ©2020-2022 as I think it makes more sense, since the contributions were made during these years, and not only in 2022.

But I guess this is just a minor detail.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Since this is a legal topic, then the Open Source Team would need to decide. If you Google "copyright years websites" you can read some opinions on this.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Agreed (-:

Hope you have an relaxed Saturday! 🙂

**Comment by Ein-Tim** [comment]
Okay, [this](https://www.quora.com/If-you-update-a-site-does-the-copyright-year-change) site says:

> Thus we will often see notices like this:

> © 1999–2017 Behemoth Corporation. When using this format the first date represents the year the site was launched. The second date represents the year in which the most recent content was added.

> It would also be appropriate to use © 1999 Behemoth Corporation.

> But we would **not** want to use © 2017 Behemoth Corporation if the site was created in 1999. We would only use that if the site was newly created in 2017 and did not include material that had been published earlier.

So, ©2020-2022 should be a good way to go. 👍

**Comment by MikeMcC399** [comment]
@Ein-Tim
> So, ©2020-2022 should be a good way to go. 👍

That is true for other repositories, like the app repositories or the website, which are being committed to almost daily. It would not be right for this repository though.

The [README.md](https://github.com/corona-warn-app/cwa-hotline/blob/master/README.md) asserts copyright:

"_Copyright (c) 2020-2021 Deutsche Telekom AG and SAP SE or an SAP affiliate company._"

which is correct as far as the dates are concerned and should not be changed at this time.

Copyright can only refer to commits to the repository, of which there are only 7 so far:

- The first commit was https://github.com/corona-warn-app/cwa-hotline/commit/11228fd3478ec014b8060ab381664fbc60b9aaf7 on 19 Jun 2020.
- The most recent commit was https://github.com/corona-warn-app/cwa-hotline/commit/6fbdd069984b322ba9af9718165af110c06f161d on 25 Jun 2021.

Since there has been no commit in 2022 so far, it would not be correct to change the copyright year to include 2022. That would just be misleading.

**Comment by Ein-Tim** [comment]
Mike's right, as always. Closing.

**Comment by Ein-Tim** [comment]
FYI: To all other PR's I added the note to only merge them after a change to the content of the repository was done. 

However, I'll leave this PR closed, as the hotline repo is probably the one with the least frequent changes. If a change should be done, the author of the PR should remember to bump the copyright year.

**Pull request closed without merging**
